feature reusable component
imrealashu/vue-vis pull request #1
Opened 2017-03-18 16:39 UTC by euledge

We made multiple components at the same time.

2017-03-18 17:28 UTC, imrealashu requested changes
mounting the root instance to `body` or `html` tag is not recommended on vue 2. https://github.com/vuejs/vue/releases/tag/v2.0.0-rc.3

Please make mount it on a `div` tag as it was..

2017-03-18 17:28 UTC, imrealashu commented on script.js
> -	el: 'body',
any specific reason for mounting the the root instance to `body` tag ? @euledge

2017-03-19 23:38 UTC, euledge commented on script.js
> -	el: 'body',
I use mount to  `#app ` instead of  `body`.  
we know the way recommended on vue 2.
should split commit?

2017-03-20 07:11 UTC, imrealashu commented on script.js
> -	el: 'body',
just change `el: 'body'` to `el: '#app'` in the source code.

2017-03-20 09:44 UTC, euledge commented on script.js
> +	el: '#app',
looks to changed  `el: #app`

2017-03-20 09:46 UTC, imrealashu commented on script.js
> +	el: '#app',
cool 👍

2017-03-20 09:46 UTC, imrealashu approved these changes

2017-03-20 09:46 UTC, merged

2017-03-20 09:49 UTC, imrealashu commented
@euledge merged. also you can use it anywhere you want and PRs will be appreciated.

2017-03-20 13:45 UTC, euledge commented
@imrealashu Thank you for merge. I 💛 Vue.js

2017-03-20 14:15 UTC, imrealashu commented
are you on larachat ? let's have some word there ?